# site settings
title: Pulickal 
subtitle: Ramblings and Reposites
email: tony@pulickal.net
description: A personal portfolio, blog, and dumping ground built on Jekyll 
baseurl: "/" # the subpath of your site, e.g. /blog
url: pulickal.net # the base hostname & protocol for your site
author: Tony Pulickal
street_address: 1234 Somewhere Road
city: Anyplace 
state: NJ
zip_code: 12345 
country: United States of America
phone: (123) 456-7890 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/FeralGroundhog
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/tonytpulickal
linkedin_url: https://www.linkedin.com/in/tonypulickal 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/Tony_Pulickal 

# build settings
markdown: kramdown

sass:
  style: compressed
